language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: required
services:
  - docker
env:
  global:
  - OPAMERRLOGLEN=0
  - PINS="capnp:https://github.com/talex5/capnp-ocaml.git#interfaces"
  - PACKAGE=capnp-rpc
  matrix:
  - DISTRO=debian-9 OCAML_VERSION=4.04.0
